### ISSUE TITLE
Unable to move windows with pointer after a while

### ISSUE THREAD

**Issue by Bridouz** [JLErvin/berry#104]
Hi, Thanks for `berry`, a really nice tiny wm which stay out of the way and let us use our computer.

However I have an issue (noticed on Alpine Linux (Musl Libc/Busybox) and Debian (Glibc/coreutils)

After a while windows can't be moved with pointer. It does nothing. Killing `berry` and restarting the X server solves the issue. I do not know what's causing this. Just a few minutes ago it was when I invoked `dmenu`...

Do not hesitate to requests logs if you want. (Although I do not know how to check `berry` logs)

Thanks

**Comment by JLErvin** [comment]
hmmm I've never ran into this myself. can you try replicating it and posting some logs. You can generate logs by starting `berry` as
```bash
berry -d > /tmp/log 2>&1
```

**Comment by Bridouz** [comment]
OK I ran into the bug once again.

Logs show nothing regarding that issue : 

```
berry: Drawing the following text
berry:    justin@debian: ~/Labs/berry
berry: Text height is 13
berry: Drawing text on client
berry: Drawing the following text
berry:    justin@debian: ~/Labs/berry
berry: Receieved new 22 event
berry: Handling 22 event
berry: Handling configure notify event
berry: Found 1 screens active
berry: Screen #0 with dim: x=0 y=0 w=1600 h=900
berry: Receieved new 22 event
berry: Handling 22 event
berry: Handling configure notify event
berry: Found 1 screens active
berry: Screen #0 with dim: x=0 y=0 w=1600 h=900
berry: Receieved new 12 event
berry: Handling 12 event
berry: Handling expose event
berry: Text height is 12
berry: Drawing text on client
berry: Drawing the following text
berry:    emacs@debian
berry: Receieved new 22 event
berry: Handling 22 event
berry: Handling configure notify event
berry: Found 1 screens active
berry: Screen #0 with dim: x=0 y=0 w=1600 h=900
berry: Receieved new 10 event
berry: Receieved new 9 event
berry: Handling 9 event
berry: Receieved new 7 event
berry: Receieved new 33 event
berry: Handling 33 event
berry: Recieved event from berryc
berry: Receieved new 10 event
berry: Receieved new 9 event
berry: Handling 9 event
berry: Receieved new 4 event
berry: Handling 4 event
berry: Handling button press event
berry: Receieved new 4 event
berry: Handling 4 event
berry: Handling button press event
berry: Receieved new 33 event
berry: Handling 33 event
berry: Recieved event from berryc
berry: Receieved new 4 event
berry: Handling 4 event
berry: Handling button press event
berry: Receieved new 33 event
berry: Handling 33 event
berry: Recieved event from berryc
berry: Receieved new 4 event
berry: Handling 4 event
berry: Handling button press event
berry: Setting Screen #0 with active workspace 0
berry: Text height is 13
berry: Drawing text on client
berry: Drawing the following text
berry:    justin@debian: ~/Labs/berry
```

**Comment by JLErvin** [comment]
hmmmmmm. yeah the logs aren't telling us much. can you also post your `.xinitrc` (assuming you're starting the X server that way), your `autostart` and your `sxhkdrc`? I'm not able to replicate anything on my end. do you have any more details about replicating this? is it immediately after you start dmenu, or just randomly?

**Comment by Bridouz** [comment]
I've juste tried this morning with défaut `autostart` ans `sxhkd` (berry exemples), `xinitrc` only sets `setxkbmap` to `fr`, starts `sxhkd` ans `exec berry`.

It worked this morning but when I got back from work I rang into the same issue.

It may ne related to `slock` (screenlocker). I really do not know what's the cause.

**Comment by JLErvin** [comment]
hmmmm, yeah I'm not having any luck replicating this. I've gone ahead and pushed some logging improvements and a _potential_ fix to the development branch huckleberry. You can try pulling from there if you like and seeing if it eliminates your problem, or potentially adds something to the logs to help us debug.

**Comment by Bridouz** [comment]
Tested `huckleberry` branch (what is `hucklberry` branch ?), still no luck...

I really do not know what's the cause of all of this fuss.

**Comment by Bridouz** [comment]
Closing, don't know why it hangs on my  computer, does not hang on wife's one.
