### ISSUE TITLE
Blank screen with cursor on startup

### ISSUE THREAD

**Issue by Melonai** [JLErvin/berry#105]
Hi!

I recently decided to test out some window managers and berry caught my eye as being an interesting pick.
However I can not get berry to work, all I see when I start the Xorg server is simply a black screen with a default cursor, just as another issue described here: https://github.com/JLErvin/berry/issues/87

Piping stdout and stderr to a log file didn't help, as I only see received events from sxhkd through berryc and no errors.
I've made sure both sxhkd and xinit work exactly as expected.
I'm running Arch on a ThinkPad, if that helps.

Thanks a lot!

**Comment by JLErvin** [comment]
So you're starting `berry` from the tty I'm assuming. i.e., you have a `.xinitrc` file and you launch `berry` by running `startx`?

If you want to look at log files just have `berry` run in debug mode and redirect standard error to a file. Something like:
```bash
#!/bin/bash
# this is your .xinitrc file

sxhkd -c /path/to/config/file/sxhkdrc &
exec berry -d > /tmp/log.txt 2>&1
```

**BUT**, I'm not totally convinced anything is _wrong_ here. This is exactly how `berry` should behave. You run `startx` and it launches into a black screen with a cursor. `berry` doesn't give anything else to you. If you want to set a background or have a system bar, it's up to you to set those up. I've even outlined some applications that might help with this in the [secondary applications](https://berrywm.org/usage.html) section of the documentation. Do you have a key binding to open a terminal? If that key combination doesn't work then we might have an issue, but that wasn't something included in your writeup.

**Comment by Melonai** [comment]
Yep I'm starting berry from `.xinitrc`, which currently looks like this:
```bash
#!/bin/bash

sxhkd &
exec berry -d 2>&1 | tee /home/mel/berry.log
```

And here's my `sxhkdrc` file (located in `~/.config/sxhkd`):

```
super + Return
	/usr/bin/fish

super + alt + p
	touch /home/mel/test.file
```

I've made sure the second bind is working properly, however, as you've said, I can't get a terminal to pop up. In my case I'm trying to use `fish`, but I've tried the same with `/bin/bash`. I've also tested other key bindings to open the terminal, but I couldn't get anything else to work either.

**Comment by JLErvin** [comment]
`/usr/bin/fish` isn't a terminal, it's a shell. You'd want something like
```
super + return
    urxvt
```
`urxvt` is the terminal I use, but that could also be something like `xterm` or `xfce4-terminal` or `gnome-terminal` or any other alterntaive.

**Comment by Melonai** [comment]
I knew I'd trip up on something as easy as this!
After switching out `fish` for `st` everything started working as expected.

Thanks for the quick reply! ^^

**Comment by JLErvin** [comment]
Glad I could help :)
