### ISSUE TITLE
Unexpected Crash

### ISSUE THREAD

**Issue by cjhillbrand** [JLErvin/berry#116]
Hello,
Long time berry user and fan. I have recently adopted a second monitor into my linux setup and I have been configuring berry to play nice with the new setup. I believe I am a close, but I believe there may be some unexpected behavior.

**Issue**
Berry crashes and returns me to the initial log in terminal.
**Repro**
1. On primary monitor draw a window.
2. On secondary window draw a window (or drag a window from primary to secondary)
3. Attempt to draw a new window (I used super + enter for this)

Please let me know if there is any more contextual info I can provide, or if this is simply a user mis-configuration.

**Comment by JLErvin** [comment]
What version of `berry` are you using (i.e. `berry -v`)
