### ISSUE TITLE
Unable To Compile on Arch Linux

### ISSUE THREAD

**Issue by avcado** [JLErvin/berry#121]
Things I ran
```
$ ./configure
$ make
    Compiling client.c ...
client.c: In function 'fn_int_str':
client.c:171:48: error: 'WORKSPACE_NUMBER' undeclared (first use in this function)
  171 |     Xutf8TextListToTextProperty(display, list, WORKSPACE_NUMBER, XUTF8StringStyle, &text_prop);
      |                                                ^~~~~~~~~~~~~~~~
client.c:171:48: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:33: client.o] Error 1
```
I'm running arch linux x86_64

**Comment by JLErvin** [comment]
hmmm, pulling from the latest version of `master` I don't have any issues running the commands listed. 

What is the output of `make --version`?

**Comment by Jimmysit0** [comment]
I have the same issue. Here's the ouput of make --version 

GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by avcado** [comment]
```
$ make
    Compiling client.c ...
client.c: In function 'fn_int_str':
client.c:171:48: error: 'WORKSPACE_NUMBER' undeclared (first use in this function)
  171 |     Xutf8TextListToTextProperty(display, list, WORKSPACE_NUMBER, XUTF8StringStyle, &text_prop);
      |                                                ^~~~~~~~~~~~~~~~
client.c:171:48: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:33: client.o] Error 1
$ make --version
GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by avcado** [comment]
bump

**Comment by rachejazz** [comment]
@avcado as it looks,the error is thrown during compiling and the Makefile informs you the compiler used `$CC=gcc`. What is your gcc version? Current running is 11, mine is at 10.2

**Comment by avcado** [comment]
running `gcc -version` i get 10.2.0

**Comment by JLErvin** [comment]
I'm having trouble reproducing, but I am indeed looking into it....

**Comment by avcado** [comment]
A strange thing I've noticed is it seems to be only arch. I've tested it on Ubuntu, Void, and Gentoo, and they both compile correctly. I think it has to do with `gcc` on Arch/Artix.

**Comment by rachejazz** [comment]
I'm using vanilla Arch too. Didn't face any error while compiling. I'm in a real short of time to investigate this myself. I hope @JLErvin is looking into this

**Comment by JLErvin** [comment]
@msharov any thoughts on this?

**Comment by msharov** [comment]
WORKSPACE_NUMBER is defined in config.h, which is generated by configure from config.h.in. config.h is included from client.c and I see no defines of it anywhere else. I am unable to reproduce the problem.

You should try `cpp -E client.c` and see what gets written to fn_int_str. config.h should be mentioned near the top of the output.

**Comment by avcado** [comment]
update: it compiles
