### ISSUE TITLE
Bit clearer documentation on keybindings

### ISSUE THREAD

**Issue by namespace-miata** [JLErvin/berry#124]
Few small things, and maybe I'm just stupid, but when I launch berry via startx or a display manager, no keybindings work. I'm somewhat familar with sxhkd because previously I used bspwm, however the docs say nothing about autostarting it or placing the bindings file in its config directory or even installing it. Putting sxhkd in the autostart file doesn't seem to fix it either, so if anyone can help please do it is appreciated

**Comment by namespace-miata** [comment]
Ok I noticed a closed post similar to this, and I'm gonna try that, however I think updating the docs still might be a good idea for someone who is completely unfamiliar with wms

**Comment by JLErvin** [comment]
Closing this to move discussion to the `berry-doc` project: https://github.com/JLErvin/berry-doc/pull/5

**Comment by JLErvin** [comment]
@namespace-miata I've opened a pull request on the documentation repo: https://github.com/JLErvin/berry-doc/pull/5. I've created a new page for the website that walks through basic installation for total newcomers - I'd love for `berry` to be a project that's very welcoming to the less experienced.

Please leave any comments you have on that PR and we can discuss over there.
