### ISSUE TITLE
Permission denied on device access

### ISSUE THREAD

**Issue by rachejazz** [JLErvin/berry#129]
While building berry, I intended to install all the make generated files inside a different directory, other than the default (/usr/share/). Just wanted not to execute make as a root user.

Now, ofc /dev/mouse gives me Permission Denied(Saw it from x server logs). Is it because berry doesn't have root access?
Is there any other way around this other than `sudo make install`?

**Comment by JLErvin** [comment]
I don't believe this is a `berry` specific issue. You're free to put the necessary binaries (`berry`, `berryc`) wherever you please. Whether or not you can run `berry` rootless is an X server issue.

This post might be useful: https://unix.stackexchange.com/a/439107 ?

**Comment by rachejazz** [comment]
Thank you for the guidance :)
I will investigate this further. Closing
