### ISSUE TITLE
Disable edge-lock while sending windows to other workspaces.

### ISSUE THREAD

**Issue by Young-Angelo** [JLErvin/berry#132]
I like edge-lock, but boy is it frustrating to send applications to other workspaces with edge-lock on. Since you have to switch to the workspace you intended to send the application in order to let the application inside the workspace. It would be really helpful to have an option where you have the functionalities of edge-lock but without this problem.

**Comment by JLErvin** [comment]
Can you try building on the latest master and tell me if you have the same issue?

**Comment by Young-Angelo** [comment]
> Can you try building on the latest master and tell me if you have the same issue?

Ah nope, It works good. I don't have that bug anymore.

P.S: I installed berry from the void repos
