### ISSUE TITLE
Why does it hurt to put output files into source tree

### ISSUE THREAD

**Issue by zsugabubus** [JLErvin/berry#140]
I know it is configurable via `--builddir` but I have wasted minutes to find out where the output files have gone (especially I have built it in a containerized like environment).

I just would like to learn something new today and ask why `.o` -> `/tmp/make/berry` is the default location. What's the motivation behind it?

**Comment by msharov** [comment]
/tmp is usually a ramdisk, which makes the build go faster and saves the wear on your ssd.

**Comment by zsugabubus** [comment]
I already have a tmpfs spinning for this reason but who cares about it. /tmp is for temporary files and I think if the aim of the project to make people use it then the produced binary is surely not temporary. And the project advertises itself as “A healthy, byte-sized window manager”, so I guess nobody expects giga-bytes of output that would wear anybody's SSD even a little-bit.

**Comment by msharov** [comment]
Builddir contents is temporary, most of it being kept there just to speed up rebuilds during development. Even the binary is only there temporarily until install. I would consider such a dir full of temporary files to belong in /tmp. So what exactly is your complaint here? If you are trying to suggest a better default builddir location, let's hear the arguments for it.

**Comment by zsugabubus** [comment]
Source code is not temporary then? It is also not needed after installation.

And I'm not immediately install programs (as make finished); I'm not on Windows.

- My biggest complaint is that it adds unnecessary complexity for nothing.
- If project is small, it can be compiled in one step quickly and you do not have to care where compiler puts its temporary files (/tmp). And for bigger projects it is more than good to keep these "temporary files" around.
 - Placing files outside of a project tree makes absolutely no sense. How do you know that something outside is writable, removable... etc.?
- User clones repo, hits make. User waits, waits... and the result it placed inside a dotdir pointing to a temporary location. Not accidentally named temporary. As I mentioned above I make builds inside a container so bye-bye /tmp and the binary I have waited for so long is nowhere.
- With git bare/worktree you can place your files wherever you want. Everybody can decide on its own.

I would advise what most projects do: place everything under the root directory (for small projects directly, without any intermediate directories.) Make life easy.

**Comment by JLErvin** [comment]
Personally, I have no preference to either default value. Using the source tree is more simple, and I do understand the merit to that approach (especially with a project which is intentionally small). However, even small benefits to improve SSD performance are welcome - and I do admit that I like keeping my project "clean" without lots of `.o` files everywhere.

Since this value is configurable, I'm in no hurry to make a change for it. Should more users want to use the source tree, then we can switch it back. But, for now, I'm more inclined to keep it the way it is.

**Comment by zsugabubus** [comment]
Thanks for the feedback.

> even small benefits to improve SSD performance are welcome

Replace 4 (four) spaces with a single tab. (Means 10K, not kidding.) Configure your kernel properly. Work on tmpfs. Use bare repository.

```
$ du -ah .o/ wm.c
44K	.o/berry
68K	.o/wm.o
4.0K	.o/wm.d
20K	.o/berryc
12K	.o/client.o
4.0K	.o/client.d
4.0K	.o/utils.o
4.0K	.o/utils.d
0	.o/.d
160K	.o/
76K	wm.c
```

We can state that saving "wm.c" is true SSD killer.

> I like keeping my project "clean" without lots of .o files everywhere

Am I right that we speak about a project with 3 C source files? Code is distributed like 1, 9 and 90%, so if you modify "wm.c", recompiling other two basically has no cost.

> Using the source tree is more simple

@ lowercasename from issue tracker:
> Hiya, loving berry to bits - such a lovely Unix experience

Simple, straightforward and you go the other way. I do not get it...


###### If you really care about resource usage that much, do you okay with starting a new process on every window switch?

**Comment by msharov** [comment]
There is no need to get hysterical. I get it; your usual build workflow got broken and you're annoyed. But most people do not use a container to build stuff, or for anything else for that matter. When you do unusual stuff, you shouldn't expect everyone to cater to your needs or to take inane suggestions like "replace 4 spaces with a tab" or "work on tmpfs".

As for simplicity, using a builddir simplifies life for us developers. We are not trying to make your life difficult, we are making ours easier. Source files are easier to see when no temp build files are around. Rebuilds are faster. git will not accidentally check in a dependency file. Many projects are using builddirs for these and other reasons. gcc and Xorg, for example. Once you are using a builddir, its location makes no difference in Makefile complexity, and /tmp really is the obvious place to put it. So why don't you try fixing *your* workflow instead and stop using containers where they aren't needed?

**Comment by lowercasename** [comment]
As I've been tagged, I do just want to point out that as far as Unix experiences go, the FSH standard states that "The /tmp directory must be made available for programs that require temporary files." As the program in this case is a makefile, the end result of which is a binary, the output source files _are_ its temporary files. Feels pretty Unixy to me 🙂

**Comment by zsugabubus** [comment]
> There is no need to get hysterical.

Called pure facts in my language.

> even small benefits to improve SSD performance are welcome

> you shouldn't expect everyone to cater to your needs or to take inane suggestions like "replace 4 spaces with a tab" or "work on tmpfs".

Get it? If you find it funny, how much .o -> /tmp differs then?

Other answers in order: exclude files; if /tmp goes away it is not faster/FS cache; (global) .gitignore for such accidents; GCC+XOrg in the red corner, berry in the blue–maybe there is some _little_ difference?; one more configuration option: adds complexity; in real life, I also keep valuable files in trash, hoping that my mom will not empty it one day; needed because of the fear that a Makefile touches/unlinks file outside source tree (of course also accidentally).

> As the program in this case is a makefile, the end result of which is a binary, the output source files are its temporary files. Feels pretty Unixy to me

~Yes, yes, yes... eh noo. Binaries are also in /tmp. That's the issue. As you also said, it is the end result. That is permanent. 

> FSH standard

Wow, standards. Reading [the remaining one sentence](https://www.pathname.com/fhs/pub/fhs-2.3.html#TMPTEMPORARYFILES) from the two:

> Programs must not assume that any files or directories in /tmp are preserved between invocations of the program.

(Reading `man file-hierarchy` should tell similar story.)

**Comment by JLErvin** [comment]
In all honesty, I don't find this discussion particularly productive. I appreciate the feedback and that you're passionate about the topic. But like any project, there are design decisions that are made and they can't do everything perfectly. I know you'd probably say that the trade-offs scew the other way and that we made the wrong choice - but I respectfully disagree. 

From my perspective, we have a robust build system that works for 99% of use cases. For those that it doesn't (i.e. containerized environments) there is a configurable value that allows the behavior you want. And, as a maintainer of this project, there are much issues to tackle than the default value of the build directory. You're welcome to keep discussing this if you'd like, but I don't think I'll engage with this conversation in the interest of time.

**Comment by zsugabubus** [comment]
> I don't find this discussion particularly productive

Instead of this sentence and the followings you could prove my wrong, but... yup, neither me. I feel you do not react to any of my thoughts, it does not count how hard I try to reason. But in the end I do not really care about it, I am not a berry user so what I can say is: See you. Have a nice life!
