### ISSUE TITLE
Issue when installing using trizen(maybe?)

### ISSUE THREAD

**Issue by zion1004** [JLErvin/berry#142]
Can someone explain why this happening? I'm assuming its trizen, but I dunno. Have no issue building from source though. Srry for bad English. 

![image](https://user-images.githubusercontent.com/26509174/124532518-af4e7480-de4b-11eb-9911-8a9d0bfb382e.png)

**Comment by lowercasename** [comment]
The poster in [this issue](https://github.com/JLErvin/berry/issues/141#issue-936556940) mentioned that the AUR package is broken, perhaps this is the same issue. Try seeing if the issue occurs if you build from source?

**Comment by vzzrd** [comment]
@lowercasename Can confirm that the issue I was referring to. This was already fixed once by the maintainer ([here](https://aur.archlinux.org/packages/berry-git/#comment-730198)), not sure why it started happening again

**Comment by JLErvin** [comment]
This is likely my fault - I inherited the AUR package recently and have done an exceptionally poor job of maintaining it. I'll look into it.

**Comment by JLErvin** [comment]
Howdy, can you try installing again?

**Comment by zion1004** [comment]
It is working now. Trizen isn't giving error anymore. Should I close the issue?

**Comment by JLErvin** [comment]
I'll close it - thanks for reporting!
