### ISSUE TITLE
Installing files in a pacman fakeroot environment fails without access to '/usr/local'

### ISSUE THREAD

**Issue by FlashDaggerX** [JLErvin/berry#17]
The package in the AUR fails to build because the `Makefile` tries to install it in the **real** filesystem root. When building pacman packages, a **fakeroot** is created so the files owned by the package can be placed in the filesystem properly.

I pushed a patch upstream to the AUR so the package builds properly. Here's the patch currently in upstream:
```
diff --git a/Makefile b/Makefile
index 6e25cbf..cc4f066 100644
--- a/Makefile
+++ b/Makefile
@@ -14,8 +14,8 @@ all:
 
 install:
 	mkdir -p "$(DESTDIR)$(PREFIX)/bin"
-	install $(__NAME__) "/usr/local/bin/$(__NAME__)"
-	install $(__NAME_C__) "/usr/local/bin/$(__NAME_C__)"
+	install $(__NAME__) "$(DESTDIR)/usr/local/bin/$(__NAME__)"
+	install $(__NAME_C__) "$(DESTDIR)/usr/local/bin/$(__NAME_C__)"
 	cd ./man; $(MAKE) install
 
 clean:
```

**Comment by JLErvin** [comment]
This looks good to me and successfully builds locally. Go ahead and open a pull request and I can merge.

**Comment by FlashDaggerX** [comment]
That's why I opened the issue. I know it breaks the workflow, but I prefer not doing pull requests if I don't have to.

**Comment by JLErvin** [comment]
Ok. I'll make the changes. Thanks for doing this.

**Comment by FlashDaggerX** [comment]
I noticed that you reverted the change. Was there some sort of issue?

**Comment by JLErvin** [comment]
Ah yes I was going to ping you about this soon. The package builds with the patch so long as I don't change the Makefile. Making the changes here cause the build to fail, however.

**Comment by FlashDaggerX** [comment]
I'll keep the patch upstream in the AUR for now. This'll be on my #TODO when the issue occurs again.

**Comment by jolupa** [comment]
Hi! Trying to make a package for crux but the problem is the same, I can't use the fakeroot to build the package and the patch is not working... Is possible to change the make file to use fakeroot?
Thanks!

**Comment by FlashDaggerX** [comment]
> Hi! Trying to make a package for crux but the problem is the same, I can't use the fakeroot to build the package and the patch is not working... Is possible to change the make file to use fakeroot?
> Thanks

@jolupa  The patch I have above worked for _JLErvin_ for a little while, but had to go back to his previous version because there were build errors.

The patch above suggests using an environment variable during build, in which you set the fakeroot to the current folder. In your _PKGBUILD_'s  `build()` function, suffix the call to make (or whatever) with `DESTDIR="$pkgdir"` and make sure it's present in the _Makefile_ like above.

**Comment by jolupa** [comment]
@FlashDaggerX Oh! thank you that worked!
But I think that needs to be some easy way of doing the install in a fakeroot for packages building.
Thanks.

**Comment by JLErvin** [comment]
@jolupa if the included makefile were like the one that @FlashDaggerX included above, does the build work?

**Comment by jolupa** [comment]
@JLErvin Yeah! it worked perfectly... In a few minutes I will try it to see if it works!
Thanks.

**Comment by JLErvin** [comment]
Ok I'll push a commit that changes the default Makefile to the one above. I believe that the patch breaks if we use the new makefile instead of the old one. Once I push, can you remove the patch? @FlashDaggerX

**Comment by FlashDaggerX** [comment]
Will do. Something is bothering me though, because this wasn't happening a few weeks ago. I can't find any significant changes to your makefile, so something must've changed on Arch's side.

**Comment by FlashDaggerX** [comment]
Not relevant in current master (83dfb3d), will open once it occurs again.
