### ISSUE TITLE
How to reload berry?

### ISSUE THREAD

**Issue by arcolinuxz** [JLErvin/berry#171]
Is there a command we can run to reload berry and its autostart?

super + shift + r  in sxhkd is for us restart.
https://github.com/arcolinux/arcolinux-berry/blob/7d843d6aa7461bb620d26444bef1ecb6d551c95b/etc/skel/.config/berry/sxhkd/sxhkdrc#L52

**Comment by arcolinuxz** [comment]
Arch Linux - ArcoLinux
berry-git-git+972f953-1-x86_64.pkg.tar.zst

**Comment by arcolinuxz** [comment]
in the meantime I have created my own package
AUR is behind and not correct - missing man files
![2022-01-29_11-55](https://user-images.githubusercontent.com/36679406/151658358-36216377-c949-42a6-905a-776ad7bc599e.png)

**Comment by JLErvin** [comment]
`berry` doesn't have a command to reload on-the-fly. However, such a command is generally unneeded as `berry` is configured at runtime by the commands sent through `berry`. The `autostart` file is just a shell script, and there's nothing stopping you from running it anytime you want.

**Comment by real-99** [comment]
As @JLErvin said, its preferable to use the `berryc` CLI to change berry's settings. If you want to reload the config file anyway, you can use the following snippet inside `~/.config/berry/sxhkdrc`:
```
super + shift + r
    bash $HOME/.config/berry/autostart
```
