### ISSUE TITLE
Picom

### ISSUE THREAD

**Issue by arcolinuxz** [JLErvin/berry#173]
Can picom work with berry?

Re-edit - I was able to have part of picom working at one time -  it seems it is the transparency that is not working.
Fading and shadow worked.

Tried changing settings in the config.
Tried different picom versions.
![2022-01-29_11-53](https://user-images.githubusercontent.com/36679406/151658314-2360bb04-7f64-41f5-bf03-708046d50302.png)

Here is my picom.conf

https://github.com/arcolinux/arcolinux-berry/blob/main/etc/skel/.config/berry/picom.conf

**Comment by arcolinuxz** [comment]
![Uploading ArcoLinux-2022-01-29-1643453500_screenshot_1920x1080.jpg…]()

**Comment by arcolinuxz** [comment]
On the same computer I install Bspwm with same picom application and same picom configuration.
![ArcoLinux-2022-01-29-1643454406_screenshot_1920x1080](https://user-images.githubusercontent.com/36679406/151658661-6f236534-f794-4056-af81-67920d3e4586.jpg)

**Comment by JLErvin** [comment]
This is a known issue and is an artifact of the way that `berry` draws window decorations. Decorations in `berry` are simply larger "fake" windows drawn behind each application. It would certainly be possible to refactor `berry` to use a more complex decoration scheme which doesn't do this, but it's not something I will have time to implement soon. I'm always open to reviewing PRs should someone else implement this...
