### ISSUE TITLE
Multi monitor and wallpaper...

### ISSUE THREAD

**Issue by nobobo1234** [JLErvin/berry#18]
Hey! I love your WM, have been playing with it for the whole day now. I still got a few questions.
1. How can I make it so I can use 2 monitors for 1 workspace. E.g. when I move a window to another monitor and switch workspaces or reload berry it will switch back to the other screen. Same for when I press `f` or `m` to maximize the window.
2. How can I apply a wallpaper. I tried using `squash` but that didn't work.

EDIT: Found out how I could apply the wallpaper (hsetroot). But it doesn't work well with my 2 monitor setup. It stretches along my two monitors.

Thanks in advance!

**Comment by JLErvin** [comment]
Question 2 isn't manage at all by `berry` so I won't address that here. You can try using `xsetroot`, `hsetroot`, or another wallpaper application like `nitrogen` to manage this.

As for your second question, I would like to clarify a few things. You have associated workspaces with monitors and then manually move a window from one monitor to another. And now you want the window to be associated with that desktop when you switch focus to it? So `berry` should be able to handle this *if* you use the `send_to_workspace` function in `berryc`. However manually moving the window using your mouse or keyboard will not pick up the change and the window will still be associated to its original desktop.

If this is your problem then the current solution should be using the `send_to_workspace` function. If being able to move windows and have them automatically switch desktops is something you would like me to implement you can add a feature request here on github.

**Comment by nobobo1234** [comment]
No, sorry if I was unclear. The problem is that I want a workspace to be able to 'use' multiple monitors. So that, for example, workspace one is associated with monitor one and two and I can freely move windows between the two. And that if I press `mod+f` or `mod+m` that it will go fullscreen or maximize on the monitor it's currently on.

**Comment by nobobo1234** [comment]
Oh and one more thing, it seems like when using this with compton's `blur-background` it takes the background to be the border radius and not the actual background I set.
