### ISSUE TITLE
cannot set default workspaces as 1-5 (removing ws 0)

### ISSUE THREAD

**Issue by moilong** [JLErvin/berry#194]
This is my sxhkdrc config
super + {1-5}
    berryc switch_workspace {1-5}
super + shift + {1-5}
    berryc send_to_workspace {1-5}
But berry opens with workspace 0. When I switch workspace windows in ws 0 lost permanently. After switching to another workspace there is no ws 0 until I restart berry.

**Comment by JLErvin** [comment]
Yeah, your `schkdrc` isn't configured properly. Looking at the provided sample configuration, you'll want something like this:
```
super + {1-9}
    berryc switch_workspace {0-9}

super + shift + {1-9}
    berryc send_to_workspace {0-9}
```
`berry` workspaces are 0-indexed, whereas you likely want your keyboard to be 1-indexed.

**Comment by moilong** [comment]
> Yeah, your `schkdrc` isn't configured properly. Looking at the provided sample configuration, you'll want something like this:
> 
> ```
> super + {1-9}
>     berryc switch_workspace {0-9}
> 
> super + shift + {1-9}
>     berryc send_to_workspace {0-9}
> ```
> 
> `berry` workspaces are 0-indexed, whereas you likely want your keyboard to be 1-indexed.

Then I should change to 0-5. Thanks.
