### ISSUE TITLE
I should be able to focus a window by clicking its contents rather that its titlebar

### ISSUE THREAD

**Issue by rice7th** [JLErvin/berry#197]
when you have multiple windows in berry, to focus one another you need to click the titlebar of each. The only problem is that, in certain situations, those titlebars are not accessible, and so i need to move half of the windows just to get that one focused. I know i could use `berryc focus_follows_pointer`, but by using that the window gets sent above all the others, and i dont want that: i want to be able to focus a window without putting it above the others. Please let me know if there's a workaround because i really need this feature.

**Comment by JLErvin** [comment]
do you have [this](https://github.com/JLErvin/berry/blob/e5bcb3f04f6b4b1a26b0966d67ae9e2cd5c77fdd/examples/sxhkdrc#L57-L58) in your `sxhkdrc`?

**Comment by rice7th** [comment]
whoops my fault
