### ISSUE TITLE
Sharing a workspace between multiple monitors?

### ISSUE THREAD

**Issue by TeknosQuet** [JLErvin/berry#203]
I like this window manager, but it seems like workspaces are limited to only one monitor each. When I move a window near the edge of one monitor, it will not move to the next; as if there is a border preventing me. Is there a way to fix this or is it an intended feature? I'm assuming it might have something to do with the window manager source code being small and just not having as much stuff implemented (hence, byte-sized), but I was just curious and I thought maybe that's the reason why.

Thanks!

**Comment by TeknosQuet** [comment]
Nevermind, I fixed it. I had to set `EDGE_LOCK` in `config.h.in` to `false`. I'm aware it says not to edit those values, but I couldn't find an option to configure it with `berryc` and it happened to work out anyway.

**Comment by JLErvin** [comment]
It should be a `berryc` option: https://github.com/JLErvin/berry/blob/c66590292dcd41ca2d9f8083d717093cff97eb15/client.c#L78

we might need to add it to the `man` page, however.

**Comment by TeknosQuet** [comment]
Oh okay, thanks. Yeah I didn't see it in neither the manpage nor your website, but I did see the option in the `config.h.in` file. I didn't think to look in `client.c` though. I'll set it that way via `berryc` then :)
