### ISSUE TITLE
Can't move window over to second screen.

### ISSUE THREAD

**Issue by PetrifiedOak** [JLErvin/berry#204]
Title explains it, whenever i try to move my window over to the second screen, it reaches a border (moving my cursor works fine).

I compiled berrywm from source and im using KISS linux.

**Comment by PetrifiedOak** [comment]
Sorry for this issue, forgot to run configure, lol.

**Comment by PetrifiedOak** [comment]
That did not fix it, sorry

**Comment by larrasket** [comment]
Same issue here

**Comment by larrasket** [comment]
Add`berryc edge_lock   "false"` to your config. https://github.com/JLErvin/berry/issues/203

**Comment by PetrifiedOak** [comment]
Sorry for never closing this, I'll close it as I don't have a second screen anymore, and I dont use X.org in general.
