### ISSUE TITLE
Support for _NET_DESKTOP_NAMES

### ISSUE THREAD

**Issue by crian** [JLErvin/berry#29]
Can you add support for _NET_DESKTOP_NAMES? 
So it is usable with polybars xworkspaces.

**Comment by JLErvin** [comment]
Just to clarify, this is something set by the window manager? For example, you would tell `berryc` to name the first virtual desktop as `browser` and this would be reported by any application that requests to know the values of `_NET_DESKTOP_NAMES`?

**Comment by crian** [comment]
This should add compatibility for programs and bars (polybar) which need workspace informations.
Furthermore you could add EWMH support for:
````
_NET_NUMBER_OF_DESKTOPS 
_NET_CURRENT_DESKTOP
_NET_DESKTOP_NAMES
_NET_DESKTOP_VIEWPORT
````
To make it even more compatible.

**Comment by JLErvin** [comment]
Added and tested in the development branch. I'll merge with master soon - feel free to try it out in the meantime.

Commit: 33dc9de2ab18aade3de00ad9120fa0b7bc1a96aa
[branch](https://github.com/JLErvin/berry/tree/blackberry)

**Comment by crian** [comment]
Nice! Will try it.
