### ISSUE TITLE
support for BERRY_WINDOW_STATUS

### ISSUE THREAD

**Issue by JLErvin** [JLErvin/berry#30]
I'm opening this issue to discuss one of the enhancements mentioned in the feature request thread [here](https://github.com/JLErvin/berry/issues/2#issuecomment-504780683).

Specifically the first suggestion which allows clients to query information about internal window state via `xprop`.

I've starting working on this in the development branch, and I'm open to suggestions. First, a few questions I have for users:

1) What format should the output be in? `windowcherf` reports this information in JSON. Although this is well-formatted, I fear that it it inaccessible to users without a commandline JSON parsing tool and I'd rather not require a specific external tool for use.
2) Should information about all clients be reported to `xprop -root`. Currently, window status is stored in a window-by-window basis. I fear this would be impossible without using JSON as a format. Perhaps I could introduce a `berryc` command that nicely reports this information?

Thoughts? Specifically @paoloschi

**Comment by paoloschi** [comment]
1. At this point it would be useful to know how many users are potentially interested in interacting/automating operations through scripting....
I am a self-taught old geek and therefore I can allow myself to say, against any orthodoxy (...), that storing data in JSON format and then treating them with the **jq** command from _Bash_ -very out of context, therefore...-, at least for me has been the most productive and positive discovery in many years...
For this reason the solution adopted by _Windowchef_ seemed to me excellent and appropriate and the **jq** command is not normally included in system installations but I think it is present in the official repository of each distro.
Of course to handle things this way one don't have to claim the window-manager to introduce JSON formatting!! The user can build himself a wrapper that transforms the _irregularity of expression rich_ output of the two native commands _xprop_ and _xwininfo_ into something easier to query. To be successful in this, user only need the window-manager provides enough approachable data according to the EWMH protocol!
But, again: what interest there may be in all of this from the majority of users I can not imagine. Probably the already present actions that can be bindable with hotkeys are enough for most people and a certain automation or definition of custom rules for individual windows are only need by a negligible minority.......

2. >Perhaps I could introduce a berryc command that nicely reports this information? 

Curious: when I was making the first request, I omitted to have even imagined of a 'berry**q**' command entirely dedicated to '**q**ueries', not to be confused with 'berry**c**' to be used to perform '**c**omands'...  
As for the extra function via `xprop -root`, I realize now that this is an exaggeratedly pretentious request from a window-manager. In this case also, being known by _NET_CLIENT_LIST the IDs of all the existing windows, the same can be obtained by querying them individually from the user side...

**Comment by JLErvin** [comment]
I think I'll move forward with a split approach. By default, users can use `BERRY_WINDOW_STATUS` to retrieve information about the client in a JSON format. I'll add a new `berryc` command to toggle between this and a plain-text version for users wishing to parse the information using something like `sed`. 

I've played around with the idea of something like `berryq`. My only reservation is redundancy with using `xprop` to retrieve this same information. If you can get window geometry from the xserver itself, why should `berryq` also spend time and space implementing this same functionality?

**Comment by JLErvin** [comment]
Can you post a sample `jq` command that would parse the output of something like `windowchef`?

**Comment by paoloschi** [comment]
```
# A way to extract the JSON document could be like this...
$ hint="$( xprop -notype -id 0x01a00006 WINDOWCHEF_STATUS )"
$ eval json="${hint#* = }"
$ jq <<<"$json"
{
  "window": "0x01a00006",
  "geom": {
    "x": 4,
    "y": 602,
    "width": 1902,
    "height": 584,
    "set_by_user": true
  },
  "state": "normal",
  "min_width": 143,
  "min_height": 65,
  "max_width": 6,
  "max_height": 224,
  "width_inc": 1,
  "height_inc": 1,
  "mapped": true,
  "group": -1
}

# Is the window mapped?
$ jq '.mapped' <<<"$json"
true

# Window position?
$ jq '.geom | .x,.y' <<<"$json"
4
602

# or otherwise, by interpolation
$ eval "$( jq -r '.geom | "x=\(.x);y=\(.y)"' <<<"$json" )"
$ echo $x $y
4 602
```

something like that?

**Comment by JLErvin** [comment]
Ok yeah that's perfect. I'm testing on the development branch right now but it looks like it works just fine with jq. I'll merge with master in the coming days and let you know.

**Comment by paoloschi** [comment]
awesome!

> I'll add a new berryc command to toggle between this and a plain-text version for users wishing to parse the information using something like sed.

I was thinking now: since can be added as many hints as one want with arbitrary names, is it worth touching berryc to add the new command?
the 2 formats could also coexist ...something like BERRY_WINDOW_STATUS and BERRY_WINDOW_STATUS_JSON?

**Comment by JLErvin** [comment]
Switching between the two is already implemented in the development branch [here](https://github.com/JLErvin/berry/blob/33dc9de2ab18aade3de00ad9120fa0b7bc1a96aa/src/client.c#L72).

I think I'll stick to just a single property - I can't see a use case for people needing both.

**Comment by JLErvin** [comment]
This has been merged with main for a while now. Feel free to reopen should anything else come up.
