### ISSUE TITLE
[Question] about transparency 

### ISSUE THREAD

**Issue by HedariKun** [JLErvin/berry#35]
is it possible to have transparent stuff with compton?
if now is there any plan to add something like this in future ?

**Comment by arnolddinkla** [comment]
Yes it is but you need to install compton. JLErvin has a compton config in his dotfiles.

**Comment by vaskark** [comment]
I have compton installed, and I only experience transparency when window decorations are off.

**Comment by JLErvin** [comment]
I have not implemented anything special to allow for transparency - but this should be possible using compton. Should someone want to implement this I would be open to reviewing pull requests - although I will not be implementing it personally.
