### ISSUE TITLE
send_to_workspace unintended behavior

### ISSUE THREAD

**Issue by lieuxnoir** [JLErvin/berry#36]
Steps to reproduce:
- Spawn a terminal (or any program).
- `send_to_workspace {0-9}` (`sxhkd` bindings)
- Go to previous workspace (where the window was last contained).
- The window is still there (the bug).

**Comment by JLErvin** [comment]
Looking into this now. Probably something I messed up after refactoring window draw orders.

**Comment by JLErvin** [comment]
@lieuxnoir should be fixed on the development branch as of 4b4df8c2fcf9df6a95d49460ef6b9365b7430bff . Can you try pulling/remaking from there and see if this fixes your issue.

**Comment by lieuxnoir** [comment]
I can confirm. It's working now. Thanks. :smile:
