### ISSUE TITLE
cannot support youtube videos on full screen

### ISSUE THREAD

**Issue by lieuxnoir** [JLErvin/berry#39]
Steps to reproduce:
- Open any browser (`firefox` in my case).
- Proceed to [YouTube](https://www.youtube.com) and play any video.
- Making the video full screen does not work (the bug).

Note: It works on `dwm`. I haven't tested other WMs.

**Comment by JLErvin** [comment]
> Making the video full screen does not work (the bug).

What does not work? Do you mean the application is not maximized fully (i.e. the video would take up the entire display)?

**Comment by lieuxnoir** [comment]
> > Making the video full screen does not work (the bug).
> 
> What does not work? Do you mean the application is not maximized fully (i.e. the video would take up the entire display)?

The video itself (i.e. pressing `f` during the video or clicking the full screen icon on the lower right part of the video), not the browser.

**Comment by lieuxnoir** [comment]
UPDATE: Fullscreen youtube video only works if the browser is on fullscreen (`berryc fullscreen`) as well.

**Comment by JLErvin** [comment]
Better late than never, implemented as of 86f5ab20187ffc4d7d5639da2e281c0d33492f10
