### ISSUE TITLE
centering nothing crashes berry

### ISSUE THREAD

**Issue by lieuxnoir** [JLErvin/berry#42]
Steps to reproduce:
- While using berry, go to any blank workspace.
- Press the binding for `berryc window_center`.
- `berry` crashes.

Note: This is tested on the latest commit on the `master` branch of `berry`. Untested on the latest stable release version.

**Comment by JLErvin** [comment]
Fixed as of c2c8d61319b078ab7e13115d5cca161cf513c62f. I plan on adding a few bug fixes before merging but this will be available on master soon.

**Comment by JLErvin** [comment]
Merged with master as of 0.1.3
