### ISSUE TITLE
suggestion: window_monocle

### ISSUE THREAD

**Issue by lieuxnoir** [JLErvin/berry#44]
Current behavior:
1. Open a window (any program) and remember it's size and location (optionally, you can also resize/move the window, just remember it's size and location).
2. Toggle monocle mode on.
3. Resize/move the window (while monocle mode is on).
4. Toggle monocle mode off.
5. Notice that the window is back to its initial size and location (from step 1).

Suggested behavior:
1. Open a window (any program) and remember it's size and location.
2. Toggle monocle mode on.
3. Resize/move the same window (while monocle mode is on).
4. As I do step 3, monocle mode should automatically toggle off.

**Comment by JLErvin** [comment]
I agree this behavior is better than the current one. Implemented as of dff2c811ebc31818885a160c06e85f0b660fcca5
