### ISSUE TITLE
window_monocle stops working

### ISSUE THREAD

**Issue by lieuxnoir** [JLErvin/berry#46]
Steps to reproduce:
1. Open any window (any program).
2. Enable monocle mode.
3. Disable monocle mode.
4. Enabling monocle mode once again doesn't work anymore.

Note: Resizing/moving after step 3 (and before step 4) makes monocle mode work again.

**Comment by JLErvin** [comment]
Ah, fixed in 717486bde9ddca2d984aa48c93f14d1fbff2b54c

**Comment by lieuxnoir** [comment]
Thanks! :D Closing.
