### ISSUE TITLE
window on previous workspace does not lose focus

### ISSUE THREAD

**Issue by lieuxnoir** [JLErvin/berry#48]
Steps to reproduce:
1. Open any program. I'll be using the terminal as an example.
2. Go to an empty workspace.
3. Type something on the keyboard while on the empty workspace.
4. Go back to the previous workspace where the terminal is located.
5. Notice that the input made on the empty workspace was present on the terminal.

Note: Occurs on other programs (e.g. closing a tab in firefox, etc.).

**Comment by JLErvin** [comment]
I'm amazed I never noticed this before. Credit to `vain` who implemented something similar in `katriawm`

Fixed in 5026ed72e0860df9915a8e3dcade047dc7bbae6e
