### ISSUE TITLE
Polybar just in the middle of the screen.

### ISSUE THREAD

**Issue by jolupa** [JLErvin/berry#5]
I just autostarted the polybar I use normally and in berry it shows right in the middle of the screen and is treated like other windows with borders an so on.
I'm using Manjaro and used the Aur package for Arch.

**Comment by JLErvin** [comment]
Polybar support has been added in [0.0.5](https://github.com/JLErvin/berry/releases/tag/0.0.5)

**Comment by jolupa** [comment]
Perfect! Working!
