### ISSUE TITLE
weird behavior on workspace 0 (zero)

### ISSUE THREAD

**Issue by lieuxnoir** [JLErvin/berry#52]
Steps to reproduce:
1. Go to workspace 0 (zero).
2. Open a window (any program).
3. Go to another workspace to see the bug.

Note: Immediately closing the window in step 2 will also show the bug.

**Comment by JLErvin** [comment]
Ah this was actually semi-intended behavior that worked incorrectly.

There is a question of whether or not you want to bind "Super + 1" to send you to workspace 1 or workspace 0. Personally I think it makes more sense to send you to workspace 0. I've made the relevant change in `wm.c`, but you should also change your
`sxhkdrc` to the following to get consistent behavior:

```
super + {1-9}
    berryc switch_workspace {0-8}
```
