### ISSUE TITLE
[xcb] Unknown sequence number while processing queue SIGABRT

### ISSUE THREAD

**Issue by onodera-punpun** [JLErvin/berry#54]
No idea why this happens, freshly compiled and no changed made, error:

```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
berry: xcb_io.c:263: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
fish: Job 3, '~/tmp/berry/berry' terminated by signal SIGABRT (Abort)
```

**Comment by JLErvin** [comment]
This is a curious issue since `berry` uses the `xlib` library, not `xcb`. Still, it could be something on our end - although I'm more convinced it's some difficult to track down race condition.

Could you post your log file/try to recreate the error so I can do some more thorough investigation?

**Comment by dylanaraps** [comment]
On my machine `libX11` (`xlib`) depends on `libxcb` (*I'm not sure if this is always the case*). I've come across this issue too and I was also unable to fix it. 

The steps to reproduce it on my machine are simply:

- Compile `berry` (`make`)
- Launch `berry`.
- Above error.

I'm running with `musl` `libc` for reference.

**Comment by dylanaraps** [comment]
`libX11` always requires `libxcb`:

```
# Always required
X11_REQUIRES='xproto >= 7.0.17 xextproto xtrans xcb >= 1.11.1'
X11_EXTRA_DEPS="xcb >= 1.11.1"
```

From: https://github.com/mirror/libX11/blob/master/configure.ac#L80-L82

**Comment by JLErvin** [comment]
Yes that's true - I just meant that there is no explicit `xcb` code used inside of `berry`.

Nonetheless, I'll setup a VM with some `musl`-based distro and try to debug this.

**Comment by dylanaraps** [comment]
Note: I'm unsure if @onodera-punpun is using `musl` also. This may be reproducible on `glibc` too.

**Comment by dylanaraps** [comment]
Not sure if this is of any use to you as it's related to a `rust` library, however it looks like the same issue: https://github.com/rust-windowing/winit/issues/458

**Comment by JLErvin** [comment]
@dylanaraps I saw that as well but I'm not sure if it's applicable to our problem yet.

**Comment by dylanaraps** [comment]
Found the error message in `libX11`: https://github.com/mirror/libX11/blob/823a0f8a820247b6c1e092f679b49cbdc2ea5c95/src/xcb_io.c#L33-L38

**Comment by onodera-punpun** [comment]
I'm using glibc, although I do use a source distro, so it could possible be the source of a CFLAG or kernel option I set.

**Comment by JLErvin** [comment]
@onodera-punpun I've haven't seen this issue elsewhere either. Can you post your `USE` flags (or equivalent) so I can try to recreate the issue on my end?

**Comment by onodera-punpun** [comment]
Oh wait, I didn't build this package with my package manager, so in fact I just used the default CFLAGS as defined in config.mk...

**Comment by JLErvin** [comment]
I added a potential fix. Since I still haven't been able to recreate this on my end could someone try the [development branch](https://github.com/JLErvin/berry/tree/raspberry), raspberry, and see if this fixes the issue? @onodera-punpun

**Comment by onodera-punpun** [comment]
Sadly didn't fix the issue, exact same error

**Comment by shippage** [comment]
I'm on debian 10 stable, and also am getting the same error when I run `startx /usr/local/bin/berry`

**Comment by JLErvin** [comment]
@dylanaraps can you post your global compiler options for `KISS`?

**Comment by Notevill** [comment]
I have the same issue on Void Linux. I install berry from void linux repository. Also i tried build from sources.
in my ~/.xinintrc i add 
```
berry &
exec xterm
``` 
so after `startx` i have black screen with xterm but berry not working. If i restart berry from terminal with -d option it says same errors like @onodera-punpun posted.

**Comment by Notevill** [comment]
I trying to debug this error.
[berry_log.txt](https://github.com/JLErvin/berry/files/4223218/berry_log.txt)

Testing on manjaro, berry builded from source.
At start there is no errors (line 14). But on first event (mouse click or start new application) it crushes (after line 14).

**Comment by Notevill** [comment]
I think I know how to repeate this.
I add `x` permission to `.config/berry/autostart` and now it working
if I remove `x` permission it's not working with same error

**Comment by JLErvin** [comment]
@Notevill yes! oh my goodness thank you I've been unable to recreate this for months. For now, make it executable and I'll try to find a more universal fix :)

**Comment by JLErvin** [comment]
@Notevill can you try using the development branch, `grape`, and see if this works _without_ `autostart` being executable. [branch here](https://github.com/JLErvin/berry/tree/grape)

**Comment by Notevill** [comment]
Yes, it's working
