### ISSUE TITLE
installation from aur fails on arch linux

### ISSUE THREAD

**Issue by mighty9245** [JLErvin/berry#57]
installation fails on the last step (installing built package) with the following error:
```
error: failed to commit transaction (conflicting files)
berry-git: /usr/local/share/man exists in filesystem (owned by filesystem)
Errors occurred, no packages were upgraded.
```

i guess this issue could be related to #17

**Comment by mighty9245** [comment]
seems to be the aur package issue, not the berry one. could be fixed by editing the pkgbuild and changing prefix from `/usr/local` to `/usr` (as noted on the package page, lol: https://aur.archlinux.org/packages/berry-git/). so if you encounter the same issue, just `git clone https://aur.archlinux.org/berry.git`, edit the pkgbuild and change prefix as described above and `makepkg -si`.

**Comment by FlashDaggerX** [comment]
I know this issue is long-since closed, but this bug was noted by someone on the AUR page. I'm sorry I didn't check issues sooner, but this is fixed upstream as of a few days ago.

**Comment by JLErvin** [comment]
@FlashDaggerX no worries, thanks for the fix :)
