### ISSUE TITLE
Change prefix of manpage install - current target is a symlink.

### ISSUE THREAD

**Issue by FlashDaggerX** [JLErvin/berry#6]
Instead of opening a PR, just doing this to save time. The current `MANPREFIX` throws a build error when using the AUR installation.

Under `config.mk`:
```
-MANPREFIX = $(PREFIX)/share/man
+MANPREFIX = $(PREFIX)/man
```

When building, `MANPREFIX = $(PREFIX)/share/man` is owned by the filesystem, and aborts the package update. Seeing as how this points to `/usr/local/man` anyway, it should go there instead.

**Comment by FlashDaggerX** [comment]
And while I'm here, the installation instruction in your README is wrong. The package is called `berry-git`, so the command would be

`yay -S berry-git`

**Comment by JLErvin** [comment]
Should be fixed in https://github.com/JLErvin/berry/releases/tag/0.0.5

**Comment by FlashDaggerX** [comment]
Both issues have been fixed

Closing.
