### ISSUE TITLE
numerations of workspaces

### ISSUE THREAD

**Issue by camillelab** [JLErvin/berry#63]
Thank you for this simple and beautiful window manager! I have a problem when I send a window to another workspace.

`send_to_workspace 2` sends the current window to workspace 1
`send_to_workspace 1` sends the current window to workspace 0
and i am not sure what `send_to_workspace 0` does.

**Comment by JLErvin** [comment]
Ah, this is an old OBOB that I never really cleaned up. Try pulling the latest master and updating your `sxhkdrc` to the one in the examples folder. 

2900d41c3bf920019fe1231a432935992bf52a50
