### ISSUE TITLE
Deprecate 'top_gap' for something like 'edge_gap'

### ISSUE THREAD

**Issue by linkert** [JLErvin/berry#68]
As discussed on [reddit](https://www.reddit.com/r/unixporn/comments/fg9l3b/berry_classes_canceled_time_to_rice/) I did not find a bottom_gap. Something more general like ```edge_gap``` would be neat.

```edge_gap top right bottom left``` - eg: ```edge_gap 0 0 24 0``` for a 24px bottom gap

However you choose to implement this feature it will be great!

**Comment by JLErvin** [comment]
This wound up being significanly more work than I was expecting - my geometry was not as well factored as I would have liked. Regardless, the development branch now has an `edge_gap` function.

Usage is as follows:

`edge_gap top bottom left right`

I'm opening to switching the order of those arguments if something is more standardized.

Feel free to try it [here](https://github.com/JLErvin/berry/tree/huckleberry). I will continue testing before including this in the next release.

**Comment by JLErvin** [comment]
Merged with master as of `0.1.5` :)
