### ISSUE TITLE
Window's `focus_color` appears on top of the window when clicked.

### ISSUE THREAD

**Issue by FlashDaggerX** [JLErvin/berry#7]
*Commit [`e8fea835679d233d51049d431cdb4eb05ab1262b`](https://github.com/JLErvin/berry/commit/e8fea835679d233d51049d431cdb4eb05ab1262b)*

Not really sure how to describe it, [so here's a one second video](https://youtu.be/ScKPAxa9h3Y) depicting my issue. It happens for a split second before reverting back to normal, but comes back when it's clicked. It happens to all windows, regardless of size.

*Dell Latitude E6320, stock specs*
**Arch Linux 4.18.5-arch1-1-ARCH**
**Intel Integrated Graphics** (Using the `mesa` driver)

**Comment by FlashDaggerX** [comment]
I didn't get it recorded because I just discovered it, but I also found that switching to workspaces with windows in it (Typically, fullscreen windows) are painted orange (the default `focus_color`) for a few seconds.

**Comment by JLErvin** [comment]
This and any associated flickering should be totally fixed as of 60bdf516f72d8ea7adf3e8f413ba6f9b43436e39
