### ISSUE TITLE
Best compositor settings (picom)

### ISSUE THREAD

**Issue by vaskark** [JLErvin/berry#73]
Hi. Berry was freezing when I was using picom's `glx` backend so I've switched to `xrender` and it hasn't crashed once. Although now I'm getting weird artifacts surrounding unfocused windows. So I was just wondering what others are using in their picom configs.

Here's [mine](https://justpaste.it/7k6e4).

Also, transparency only works on terminal windows when titlebars on toggled off. When on, the backgrounds are solid.

Thanks! This is a great wm. Keep up the great work.

**Comment by vaskark** [comment]
Update: turns out I had `--experimental-backends` set. I removed that and the artifacts are gone now.

**Comment by dontlaugh** [comment]
> Also, transparency only works on terminal windows when titlebars on toggled off. When on, the backgrounds are solid.

Thanks for noting this. I was having trouble with opacity using picom.
