### ISSUE TITLE
X Error of failed request

### ISSUE THREAD

**Issue by r0b0tx** [JLErvin/berry#74]
berry: font not specified, loading default font
berry: Successfully opened display
berry: Giving focus to dummy window
Fatal request. request code=2, error code=10
X Error of failed request:  BadAccess (attempt to access private resource denied)
  Major opcode of failed request:  2 (X_ChangeWindowAttributes)
  Serial number of failed request:  32
  Current serial number in output stream:  38

Manually installed from this repo and through AUR give me the same result.

Can't find an answer on internet may need some help

**Comment by JLErvin** [comment]
Can you post your `.xinitrc`

**Comment by r0b0tx** [comment]
Just copied yours from your dotfiles adapt it and now it works.

**Comment by JLErvin** [comment]
Can you post what you had originally. I would like to be able to know what caused this.
