### ISSUE TITLE
Shadows over top of window decorations

### ISSUE THREAD

**Issue by AdamChristiansen** [JLErvin/berry#75]
**Problem**

When using a compositor (compton in my case) with shadows enabled, both the window and the window decorations have shadows, and the window shadow is on top of the decorations. This is shown in the screenshot below.

![berry-shadow](https://user-images.githubusercontent.com/8989961/77007350-aae60b80-6929-11ea-983b-3c916e917ed9.png)

**Expected Behaviour**

I expect something like the screenshot below taken in bspwm. I've made an extremely large border to demonstrate. There is only a single shadow for the window + decoration, and there is no "bleeding" of the shadow on to the decoration.

![bspwm-shadow](https://user-images.githubusercontent.com/8989961/77007361-b33e4680-6929-11ea-804b-4ee0aac9f071.png)

**Details**

- berry 0.1.4
- bspwm 0.9.9
- compton 7.5

**Comment by JLErvin** [comment]
Let me see what mechanism compton uses to draw shadows. It's possible this is a product (I would guess) of the fact that berry is non-reparenting in which case this might be difficult to fix. Regardless, I'll look into it a get back to you.

**Comment by JLErvin** [comment]
Ah, this should be fixable using some compton settings. Consider adding the following to your `compton.conf`:

```ini
shadow-exclue = [
    "_NET_FRAME_EXTENTS@:c"
]
```

Try this and let me know if it gives you expected behavior.

**Comment by AdamChristiansen** [comment]
This solved it. For documentation purposes if someone else is comes across this, I had

```ini
shadow-exclude = [
    "_GTK_FRAME_EXTENTS@:c"
]
```

in my `compton.conf`, but changing it to

```ini
shadow-exclude = [
    "_GTK_FRAME_EXTENTS@:c",
    "_NET_FRAME_EXTENTS@:c"
]
```

to use EWMH as well is more general than just GTK.

**Comment by unrealapex** [comment]
I get this same issue but with transparency(shadows work fine).  How would I go about solving this? Would I disable shadows for the window type?
