### ISSUE TITLE
Window getting unregistered from _NET_CLIENT_LIST when moved to another workspace

### ISSUE THREAD

**Issue by little-nem** [JLErvin/berry#77]
It seems to me that when a window is moved toward another workspace, it is temporarily unregistered from the xserver property descriptor.

#### Environment:
- `Xor- 7.6`
- `libX11-1.6.9`
- `berry-0.1.5` (packaged by Void Linux)

#### Step to reproduce and observe:
- Open a terminal on, say, workspace `0` and make sure it is listed in `xprop -root _NET_CLIENT_LIST`
```
home ) xprop -root _NET_CURRENT_DESKTOP 
_NET_CURRENT_DESKTOP(CARDINAL) = 0
home ) xprop -root _NET_CLIENT_LIST
_NET_CLIENT_LIST(WINDOW): window id # 0x120000e
```
- Move it to another workspace, by running `berryc send_to_workspace 5 & berryc switch_workspace 5` in it.
- Observe that it has disappeared from _NET_CLIENT_LIST:
```
home ) xprop -root _NET_CURRENT_DESKTOP
_NET_CURRENT_DESKTOP(CARDINAL) = 5
home ) xprop -root _NET_CLIENT_LIST
_NET_CLIENT_LIST:  not found.
```
- (Once another window is opened anywhere, both windows are listed, so the
first one is registered again)

I think this might also be related with https://github.com/polybar/polybar/issues/1922.

**Comment by JLErvin** [comment]
Thanks for the excellent write up - I was able to fix this within minutes. Should be functional as of https://github.com/JLErvin/berry/pull/78/commits/5ab590cea3bcb7282108ee837e131d514389747c

**Comment by little-nem** [comment]
Yup it is! Thank you for such a quick fix! :smiley:
