### ISSUE TITLE
way to handle fullscreen

### ISSUE THREAD

**Issue by mintyleaf** [JLErvin/berry#79]
i know from jlervin website that he plays nice counter strike)
so today i decided to install cs and try to play on new laptop with berry as wm
and one thing is freaks me out: when in game i going to any kind of menu - window automaticly goes to maximized state from fullscreen
if jlervin plays cs under own berry wm - how he handle this situation?)
maybe some tips?

also, it would be very nice to have an option to turn off window borders when window goes fullscreen

**Comment by JLErvin** [comment]
I don't play games on my linux machine, but this is something I should probably support. Fullscreen behavior is a mess right now, so I'll install steam when I get a few minutes and see what the behavior is like.

**Comment by JLErvin** [comment]
Fullscreen behavior should be more predictable as of 0.1.6. Closing.
