### ISSUE TITLE
Minor README issues

### ISSUE THREAD

**Issue by nan0s7** [JLErvin/berry#8]
Just letting you know that the commands given in the "copy the sample configuration files" section aren't copy-and-paste-easy.

(assuming the user is still in the berry folder from installation):
`
mkdir $HOME/.config/berry
cp example/sxhkdrc $HOME/.config/berry/sxhkdrc
cp example/autostart $HOME/.config/berry/autostart
`

Changed:

- Removed the `berry/` from the second line
- Removed the "s" from `examples` as the actual folder is just `example`, from last two lines
- Removed the `berry ` from the last line, especially since there's a space there ;P

Anyway, it's not that important so keep up the great work! :D

**Comment by JLErvin** [comment]
Thanks! All this should be fixed in e8301d047883ca52c5ea4ca208eb13b077caf8e1 . See if this satisfies you and we can go ahead and close this issue.

**Comment by nan0s7** [comment]
Looks great! Can I ask, was sxhkd supposed to be started by berry upon launch? As it didn't work for me and I had to add the `sxhkd -c $HOME/.config/berry/sxhkdrc` line to my `$HOME/.config/berry/autostart` for it to work. This is *with* a display manager by the way.

**Comment by JLErvin** [comment]
No berry doesn't start `sxhkd` on its own. I want this to be as unix-y as possible so people can use whatever keyboard daemon they want. I assume most people will have their own place they want to start something like `shxkd` (maybe a custom startup script, in `autostart`, or in `.xinitrc`)

**Comment by nan0s7** [comment]
Ah yeah that makes sense then. Well consider this issue solved then! :D
