### ISSUE TITLE
Can we implement to focus on a window by hovering with the mouse over it?

### ISSUE THREAD

**Issue by TheM4ze** [JLErvin/berry#81]
Is it possible to implement something like bspwm has that you can automatically focus on that window when you move the mouse on it? 
Now we have to either write scripts,use sxhkd keybindings or press ~button1 to get it in focus.

I tried adding a thing or two in [ wm.c ] file,but couldn’t find anything that doesn’t mess up something else after recompiling. Maybe something so we can enable/disable it in terminal 
[ berryc WINDOW_HOVER_FOCUS true/false ] idk just an idea.

**Comment by TheM4ze** [comment]
This is what I tried so far in the [ wm.c ] file

Line 1703

**client_set_input**

I added 

**XRaiseWindow(display, c ->window);**

Tried removing the other one and adding that,adding both together but nothing worked so far.

**Comment by JLErvin** [comment]
Yes this is possible. I'll need to add a function that listens to `MotionNotify` events. This is fairly common so I'm happy to implement it.

**Comment by tmrod** [comment]
What's the status on this issue? I'd like this feature as well, and would be happy to implement it myself (with some guidance), or perhaps I could write some documentation if it has already been implemented.

**Comment by JLErvin** [comment]
Merged with master as of 5a9848e1316880221e77a40154e6c5b905332f7b
