### ISSUE TITLE
Inaccurate installation guide at berrywm.org

### ISSUE THREAD

**Issue by LorenDB** [JLErvin/berry#85]
The guide at berrywm.org should say to install sxhkd, and it should replace the line ```cp examples/sxhkdrc $HOME/.config/berry/sxhkdrc``` with ```cp examples/sxhkdrc $HOME/.config/sxhkd/sxhkdrc```. It took me a while to figure this out on my own.

**Comment by JLErvin** [comment]
I don't know if I would agree that this is incorrect, but I do believe it could use a clarification. If you use `sxhkd` with multiple programs, say `bspwm`, it makes sense to have multiple `sxhkd` configurations for each window manager with their respective commands. Logically, this should be stored in the `berry` config directory and you would specify upon startup which config file you read from. For example, my `.xinitrc` looks like
```bash
sxhkd -c "$HOME"/.config/berry/sxhkdrc &
exec berry -d
```
I'm happy to make some changes to make this more clear, however.

**Comment by LorenDB** [comment]
That makes sense. I just noticed that once I installed sxhkd, it wanted the config file from ~/.config/sxhkd.
