### ISSUE TITLE
No _NET_MOVERESIZE_WINDOW

### ISSUE THREAD

**Issue by TaylanTatli** [JLErvin/berry#88]
`WM doesn't support _NET_MOVERESIZE_WINDOW. Gravity will be ignored.`

I use wmctrl with slop to quickly move and resize windows but berry doesn't support `_NET_MOVERESIZE_WINDOW`.

**Comment by JLErvin** [comment]
Implemented as of fd8e2bce8a473874f264f2ef53ebb981ec5d5bdd
