### ISSUE TITLE
Minor issue with moving windows on dual-monitor setups

### ISSUE THREAD

**Issue by nan0s7** [JLErvin/berry#9]
Hey, loving your work so far.

I'm currently using a dual-monitor setup, with my left monitor being 1440x900 and my right 2560x1080.

Moving the mouse cursor around the screens works perfectly, so it respects the screen borders and all that jazz. However, if I move a window to my second/1440x900 monitor, I can move the window off the screen and it stops at an invisible border as if my screen was 1080 pixels high.

Again, it's not a huge issue. Just a little annoying as I like my windows hard-up against the screen borders, and the default incriment the keyboard moves the window is too large to do this without screen edge detection. :P

EDIT: Also noticed that tooltips/pop-up text in windows may go off the edge of the screen (on either monitor in my setup) and become cut-off or unreadable.

**Comment by JLErvin** [comment]
Using my current monitor implementation (of which there is none) this is an expected problem when using monitors with different resolutions (the secondary monitor will default to the resolution of the main monitor). I'm currently working on this for a future release so I'll keep you posted.

**Comment by JLErvin** [comment]
Full multi-monitor support has been added as of [0.0.7](https://github.com/JLErvin/berry/releases/tag/0.0.7)
