### ISSUE TITLE
X crashes when trying to stick chrome tab to from different window into one

### ISSUE THREAD

**Issue by ghifarit53** [JLErvin/berry#90]
I don't know if the same behaviour will happen when using another browser, but here's the step to reproduce

1. Open chrome, make two new tabs
2. Deattach one of the tabs so it'll become a separated window
3. Drag the tab in the separated chrome window into the first, and suddenly x will crashes

Oh, there's also some screen tearing when dragging the chrome window by clicking on its tab (should i make this into separate issue?)

I'm using the latest `huckleberry` branch that you've pushed yesterday, will test with the main branch after this

**Comment by ghifarit53** [comment]
Have tested, It's also occured on the main branch

**Comment by ghifarit53** [comment]
Again, i don't really know it's berry related or not, i also suspect chrome for it's ui redrawing mechanism

**Comment by JLErvin** [comment]
Are you using a compositor?

**Comment by ghifarit53** [comment]
no, just plain berry

**Comment by ghifarit53** [comment]
hey, it's not crashing again with the latest branch,  i'm gonna close this, thanks for the effort you put into it
