### ISSUE TITLE
Resize Mask (in huckleberry)

### ISSUE THREAD

**Issue by vaskark** [JLErvin/berry#91]
In config.h (huckleberry) the resize mask is defined as:

`#define RESIZE_MASK Mod1Mask
`

where Mod1Mask is the ALT key.

This conflicts with gui file managers like nemo and nautilus which use ALT for dragging & dropping files/folders with a context menu (move, copy, link).

Just thought I'd point this out. I changed mine to `Mod4Mask|ShiftMask` as a workaround.

Thanks for adding the move/resize features, btw. Very welcome :)

**Comment by JLErvin** [comment]
I don't have a perfect work around for this, and since this is a user changeable value I'm going to leave this to users to fix if they have conflicts with other applications. Closing.
