### ISSUE TITLE
Missing Some features.

### ISSUE THREAD

**Issue by aa1chemist** [JLErvin/berry#92]
I love this project. I know that it is in very alpha stage but its missing some things :-
1.Rules :- I like the paradigm of berrywm that how it works but rules are missing like if I use plank dock it just get hidden beneath the windows and in bspwm i faced same issue which can be fixed by rules.
2.Window Resizing :- I know that project is mainly focused for keyboard users but it would be great to have mouse support on borders to resize windows as openbox offers.
3.How to Quit :- Actually i don't diggen too deep but afaik its missing command to quit the session, like in bspwm thereis bspc quit.
4. Tiling Feature :- It should be great to have tiling option in some layout and floating also like awesome do just by clicking a button.
Btw, it can be implemented like,

berryc desktop -{f,t}
5.Installing through AUR :- I tried installing through yay(AUR helper) but its shows me some errors. So i compiled it and working but most of users choose to go with AUR.

And yes you forgot to invoke sxhkd in autostart which can be helpful to those who trying it first time..

![image_2020-07-21_10-08-30](https://user-images.githubusercontent.com/68586075/88029464-ac357800-cb57-11ea-99c0-d09bdcfde4f4.png)

6.Missing Contact :- Dear Devs,Not everyone uses github so if somebody got any problem or 
 bug they don't know where to discuss.
You can easily create a Telegram Group,it would be much helpful to noobs like me

**Comment by JLErvin** [comment]
Thanks for the issue. A few thoughts:
1. This would be a pretty substantial addition, but something that I would be willing to add. Other users have expressed interested in a rules based approach. Originally I had redirected people to [ruler](https://github.com/tudurom/ruler), but this is insufficient for managing things like drawing docs/system bars. I have some other issues to resolve, but I will keep this on my short list.
2. This is already added on the development branch. I will update here when this is merged with master.
3. This is supported via `berryc quit`.
4. I doubt this feature will ever be added. First, the algorithm for adding this would be fairly substantial, and I'm not sure how difficult it would be to implement with current factoring. Part of the motivation for having the `BERRY_STATUS` atom, accessible through x properties, is that users could write their own tiling scripts.
5. I'll ping @FlashDaggerX for this - they manage the AUR package.
6. I can set this up. I'm the only dev for this project, so people are always free just to contact me.
