### ISSUE TITLE
Questions regarding this project

### ISSUE THREAD

**Issue by Joe23232** [JLErvin/berry#94]
I am thinking of using `berry` but I have questions regarding this tiling window manager.

1. Does it use XCB or Xlib?
2. Am I able to do round corners around the Window? For example like this:
![image](https://user-images.githubusercontent.com/34926497/92305069-f4eda700-efc6-11ea-8489-cc9bfe1823de.png)
3. Am I able to add window decorations, for example maximise, minimise and close, example:
![image](https://user-images.githubusercontent.com/34926497/92305071-0a62d100-efc7-11ea-90d6-bf6ebe05ae60.png)
4. Is `berry` like XMonad where the user is given the source code and they just code whatever they want in a main file in a high level manner?
5. If 4 is true, am I able to use Rust?

**Comment by Akito98** [comment]
Hi,

I'm not the developer, and I only discovered this WM myself a few days ago, but I think I can answer some of your questions.

First of all, `berry` is not a tiling WM. It is a classic stacking window manager.
Also the dev doesn't plan to implement a tiling mode directly, instead you can write a script for this yourself. See 4. of issue #92 

Now to your questions:

1. According to [the website](https://berrywm.org/installation.html), it uses Xlib.

2. `berry` doesn't support rounded corners. I don't know it you could achieve this effect with an external program.

3. Buttons in window decorations are not supported either. See proposal 2 in [this comment](https://github.com/JLErvin/berry/issues/2#issuecomment-504780683) and the following answer by the dev. They said they would look into it, but that was over a year ago.

4. Of course you can fork the project and modify the source code to your liking. But I don't think this is expected from us. Instead you can use shell scripts and the client `berryc` to manipulate windows and everything else. See [usage](https://berrywm.org/usage.html) and [advanced usage](https://berrywm.org/adv-usage.html).

5. See previous answer. Also `berry` is written in C so if you plan to edit the source code directly, you'll have to use that.

I hope I could help you. Also, once again, I'm not the dev, so please correct me if I said anything wrong.

**Comment by Joe23232** [comment]
Thanks man :)

**Comment by JLErvin** [comment]
thanks to @Akito98 for their answer - yes there are all good responses (sorry for the delayed response).
