### ISSUE TITLE
berry windows don't respect rofi -show window

### ISSUE THREAD

**Issue by royaleconqueso** [JLErvin/berry#95]
```rofi -show window``` doesn't seem to cycle through windows. I've mapped it to a keybinding, and I've run it straight from the cli, and in both cases, it doesn't raise or refocus a second window. I've tried it on elementary OS and Gallium OS (both of which are, I guess, Ubuntu). And on both machines, rofi works as expected in windowmaker, evilwm, and openbox.

Can someone duplicate this? I don't know how to go about troubleshooting this, but I'm happy to do so if it would help. I know berry is reasonably new, but I'm happy to see your enthusiasm to turn it into a more mature, feature rich WM.

**Comment by JLErvin** [comment]
I was able to replicate this on my end - I'll get back to you shortly (hopefully)

**Comment by JLErvin** [comment]
Ok, this should be added on the [development branch](https://github.com/JLErvin/berry/tree/huckleberry) as of a342ba2f1795c1dec23ec37daf996da0305724a6. I would like to do some more testing, as I think I might have broke window resizing with certain applications... but I'll look into that. in the meantime, you can try building from that branch and enjoy your proper rofi behavior :)

**Comment by royaleconqueso** [comment]
Awesome. Thanks. I can confirm that it does break window resizing using alt-button 1 for xfce4-terminal and firefox and whatever else I throw at it, but only with the number lock key on? That seems a strange bug. Meanwhile, thanks for fixing rofi, which I use more than numberlock!

**Comment by JLErvin** [comment]
Released as of 0.1.6. Window resizing problems should be fixed as well. Closing.
