### ISSUE TITLE
Set draw_text to false but the title still appears

### ISSUE THREAD

**Issue by phuctv95** [JLErvin/berry#96]
Hi @JLErvin, I'm using **berry** window manager and I like it. Recently I've faced an issue, I set draw_text to false but the title still appears, like following:
![image](https://user-images.githubusercontent.com/20752858/94364595-bdb97400-00f4-11eb-874d-cb1129e4cd48.png)

Could you please take a look on this? Thank you.

I'm using:
- Berry on branch master (3872a74)
- ArchLinux

**Comment by JLErvin** [comment]
This is fixed on the development branch, [huckleberry](https://github.com/JLErvin/berry/tree/huckleberry). I'll close this when it's merged with master.

**Comment by JLErvin** [comment]
Released as of 0.1.6. Closing.
