### ISSUE TITLE
[not a issue] How to change the font?

### ISSUE THREAD

**Issue by TheFineBroccoli** [JLErvin/berry#97]
I noticed that the font can be changed in `config.h`, but how do I get the right "format" of the font name? I want to use IBM PLex Mono, do I just change

```C
#define DEFAULT_FONT "Monospace 10"
```

to:

```C
#define DEFAULT_FONT "IBM Plex Mono 10"
```

Or is there more to it? Because this doesn't look like the standard xft "format".

**Comment by JLErvin** [comment]
This is (semi) documented in the site docs [here](https://berrywm.org/configuration.html). You can use the `set_font` command via `berryc` to set your font. For example, to use the dina font with size 9 I would use:
```
berryc set_font dina-9
```
In terms of the actual formatting of the string, it uses the xft format which is documented in [this document](https://keithp.com/~keithp/render/Xft.tutorial). Pretty user friendly huh?

In your case, I could set the font to size 15 with the following:
```
berryc set_font "IBM Plex Mono-15"
```
Giving me the following result:
![ibm](https://user-images.githubusercontent.com/20917538/94623426-0134ef00-0269-11eb-87a1-804a382753a9.png)

**Comment by TheFineBroccoli** [comment]
Thanks for the response! I was used to this format `IBM Plex Mono:size=10` from urxvt and herbe, thanks for clarifying that. I probably won't use the titles anyway but we will see
