### ISSUE TITLE
First window on first workspace is closed after swithcing to another workspace

### ISSUE THREAD

**Issue by TheFineBroccoli** [JLErvin/berry#98]
This is problem is a bit odd. I will try to explain as best as I can.

When I open any window on the first workspace after fresh Xorg startup it gets closed after I move to any other workspace.

But If I switch to workspace 2 (or any other) and open window there, this bug does not occure.

---

And I have minor suggestion: `cycle_focus` should raise the newly focused window. I personally solved this with a script that just runs `window_raise` after `cycle_focus`.

PS: This wm is really nice, I like that it has window snapping by default so that I don't have to use wmutils, it's not as minimal as sowm, which is my wm of choice, but it runs perfectly (apart from this bug).

**Comment by JLErvin** [comment]
can you post your `autostart`?

**Comment by TheFineBroccoli** [comment]
Here you go:

```sh
#!/bin/sh

# Start sxhkd
sxhkd &

# Colors
berryc focus_color 282A36
berryc unfocus_color 282A36
berryc inner_focus_color 9AEDFE
berryc inner_unfocus_color 282A36
berryc text_focus_color 282A36
berryc text_unfocus_color F8F8F2
 
# Decorations
berryc border_width 4
berryc inner_border_width 2
berryc title_height 20
berryc set_font "IBM Plex Mono-11"
 
# Behavior
berryc smart_place "true"
berryc draw_text "true"
berryc decorate_new "true"
berryc top_gap 0
berryc edge_gap 12 12 12 12
berryc json_status "false"
```
Note: It doesn't matter if I start `sxhkd` from the `autostart` or `.xinitrc` this bug happens regardless of that

**Comment by JLErvin** [comment]
Oh, can you also post your `sxhkdrc` (I should have asked for this originally)

**Comment by TheFineBroccoli** [comment]
Don't worry about it. Sorry for the late reply

```sh
#
# Programs
#

# Terminal emulator
super + Return
    urxvt

# Launch slock
super + shift + x
    slock

#
# dmenu scripts
#

# Program launcher
super + space
    dprogs

# Power menu
super + shift + q
    dpower

# Search
super + s
    dsearch

# Notes
super + n
    dnotes

# NetworkManager menu
super + shift + n
    dwifi

#
# Herbe Scripts
#

# Info
super + shift + space
    hinf

# Volume
super + v
    hvol

#
# Other
#

# Wallpaper setter
super + shift + b
    cwlp

# Launch scrot on whole screen or the focused window
super + {_,shift + }p
    screenshot -{a,f}

# Reload sxhkd configuration
super + shift + r
    pkill -USR1 -x sxhkd

#
# Berry wm specific
#

# close and kill
super + q
    berryc window_close

# Center window
super + c
    berryc window_center

# Make window fullscreen
super + f
    berryc fullscreen

# Snap to left or right
super + shift + {h,l}
    berryc {snap_left,snap_right}

# Focus the node in the given direction
super + {h,j,k,l}
    berryc window_move {-50 0, 0 50, 0 -50, 50 0}

# Rotate focus and raise newly focused window
super + Tab
    bfr

# Focus given workspace, or send focused window to workspace
super + {_,shift + } {0-9}
    berryc {switch_workspace,send_to_workspace} {0-9}

# Pointer focus
~button1
    berryc pointer_focus

# Volume\brightness control keys
XF86AudioMute
    pamixer -t
XF86AudioRaiseVolume
    pamixer -i 2
XF86AudioLowerVolume
    pamixer -d 2
XF86MonBrightnessUp
    xbacklight -inc 10
XF86MonBrightnessDown
    xbacklight -dec 10
```

**Comment by JLErvin** [comment]
Give this a try (this change has since been added to master).

Instead of 
```
super + {_,shift + } {0-9}
    berryc {switch_workspace,send_to_workspace} {0-9}
```
use
```
super + {_,shift + } {1-9}
    berryc {switch_workspace,send_to_workspace} {0-8}
```
My guess is that `berry` is spawning you on workspace 0, and you have workspace 0 mixed up with workspace 1. When I press super + 1, I'm assuming this is the "first" workspace or the "left-most" workspace (i.e. workspace 0). But in reality you're switching to workspace 1 (that is what your `sxhkd` says at least). If you just shift the mapping down one you should get the expected behavior.

**Comment by TheFineBroccoli** [comment]
That was it! I was looking at the examples, idk how I didn't see this
