### ISSUE TITLE
Focus window when window contents are clicked

### ISSUE THREAD

**Issue by iBoai** [JLErvin/berry#99]
Whenever I want to switch focus to a window, it gets annoying to have to click on the titlebar to switch focus to that window. While I can use sxhkd for keybinds, I'm used to the openbox/mutter/xfwm4 way of switching focus and I don't find switching focus using hotkeys very convenient.

**Comment by JLErvin** [comment]
What version of `berry` are you using? This should be the default behavior.

**Comment by iBoai** [comment]
Running `berry -v`: `berry 0.1.5`

My `~/.config/berry/autostart`: [pastebin link](https://pastebin.com/KA6BpCnW)

**Comment by JLErvin** [comment]
Can you post your `sxhkdrc` as well? Or whatever keyboard daemon you are using.

**Comment by JLErvin** [comment]
As a guess as to why this isn't happening, you'll need the line:
```
~button1
    berryc pointer_focus
```
in your `sxhkdrc` in order to have `berry` focus windows when clicked on non-decorations.

**Comment by royaleconqueso** [comment]
I thought this question was going to be about sloppy focus (or mouse follows focus). But now that I see that it's not, can I co-opt this thread a bit? It would be nice to have an option for sloppy focus.

**Comment by JLErvin** [comment]
Closing as I believe this has been resolved, even though there hasn't been a response. Sloppy focus is already a requested feature in another issue and is being worked on.
